config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
# authenticated :user do
#   root 'businesses#index' as: :root
#   resources :businesses
# end

# unauthenticated :user do
#   root 'pages#index', as: :unauthenticated
# end
# # 
# mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

# devise_for :users
# root :to => "rails_admin::Main#dashboard"


  #resources :pages
  get 'pages/info'
  get 'pages/maps'
  root 'pages#index'
  devise_for :users
  #resources :businesses
  

  authenticate :user do
    resources :businesses, only: [:new, :create, :edit, :update, :destroy]
  end

resources :businesses, only: [:index, :show]
  resources :businesses do
    member do 
      get :delete
    end
  end

  get 'businesses/index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  validates :last_name, presence:true
  validates :first_name, presence:true
  validates :business_name, presence:true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
  before_action :authenticate_user!
  #before_filter :check_session
  require 'carrierwave'
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!
  # GET /businesses
  # GET /businesses.json
  
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
      #  redirect_to @business
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
      #  render 'edit'

        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:last_name, :first_name, :business_name, :phone, :email, :web_address, :marketing_copy,:phone_number, :mailing_address_1,:mailing_address_2, :country, :city, :state,:zip, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :check_session, :only=>[:info]
skip_before_action :authenticate_user!

  def info
  end

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/bussinesses_helper.rb
module BussinessesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, id: :business_business_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :business_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :business_last_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :business_phone %>
  </div>


    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, id: :business_phone %>
    </div>
  <div class="field">
    <%= form.label :web_address %>
    <%= form.text_field :web_address, id: :business_phone %>
  </div>


  <div class="field">
    <%= form.label :mailing_address_1 %>
    <%= form.text_field :mailing_address_1, id: :business_phone %>
  </div>


  <div class="field">
    <%= form.label :mailing_address_2 %>
    <%= form.text_field :mailing_address_2, id: :business_phone %>
  </div>


  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :business_phone %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :business_phone %>
  </div>


  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :business_phone %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :business_phone %>
  </div>
<div>
  <label>Current Image</label>
<%= image_tag(@business.image.medium.url, alt: 'Image') if @business.image? %>
  </div>
 <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
</div>



  <div class="field">
    <%= form.label :marketing_copy %>
    <%= form.text_area :marketing_copy, id: :business_phone %>
  </div>
<%# <% cl_image_upload_tag(:image_id, options = {}) %> %>
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>

<table>
  <%# <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Business name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead> %>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
      
        <td><%= business.last_name %></td>
        <td><%= business.first_name %></td>
        <td><%= business.business_name %></td>
        <td><%= business.phone %></td>
        <td>
        <a href="<%= business.image.url %>" target="_blank">
        <%= image_tag(business.image.thumbnail.url, :class => "thumbnail inline") %>
      </a>
       
        
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     
    <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %><br />
 <%= link_to "admin", "/admin"  %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p>
  <strong>Last name:</strong>
  <%= @business.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @business.first_name %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @business.business_name %>
</p>
<p>
<%= image_tag(@business.image.url, alt: 'Image') if @business.image? %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @business.phone %>
</p>



<p>
  <strong>Email:</strong><%= @business.email %></p>
<p><strong>Web Address:</strong><%= @business.web_address %></p>
<p><strong>Mailing Address line 1:</strong><%= @business.mailing_address_1 %></p>
<p><strong>Mailing Address line 2:</strong><%= @business.mailing_address_2 %></p>
<p><strong>Country:</strong><%= @business.country %></p>
<p><strong>City:</strong><%= @business.city %></p>
<p><strong>State:</strong><%= @business.state %></p>
<p><strong>Zip:</strong><%= @business.zip %></p>
<p><strong>Marketing Copy:</strong><%= @business.marketing_copy %></p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Directory</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Directory</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li ><a href="/businesses">Businesses</a></li>
        <li ><a href="/pages/info">Info</a></li>
        <li ><a href="/pages/maps">Maps</a></li>

      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    </div>
  </div>
</nav>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    AnyIsland.com <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome!</h1>
<p>This is the Index Page!</p>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>

app/views/pages/maps.html.erb
<h1>Pages#Maps</h1>
<p>Find me in app/views/pages/maps.html.erb</p>